/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 human_eye_v2.glb 
Author: ScannerDev (https://sketchfab.com/maskutfab)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/human-eye-v2-c76cd6c6d0a44bd59cb742a693a85971
Title: Human Eye v2
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/human_eye_v2.glb')
  console.log(materials);
  materials.Iris.color.set("#4b8cff")
materials.Eyeball.color.set("#ffffff")
materials.Pupil.color.set("#000000")
  
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.027}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={1.002}>
            <group scale={1.003}>
              <mesh geometry={nodes.Object_8.geometry} material={materials.Iris} />
              <mesh geometry={nodes.Object_9.geometry} material={materials.Pupil} />
            </group>
            <mesh geometry={nodes.Object_4.geometry} material={materials.Eyeball} />
            <mesh geometry={nodes.Object_6.geometry} material={materials.Cornea} scale={0.998} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/human_eye_v2.glb')
